# Generated by Django 2.0.4 on 2018-11-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20181110_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, default='30', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='width',
            field=models.PositiveIntegerField(blank=True, default='30', editable=False, null=True),
        ),
    ]
