# Generated by Django 2.0.4 on 2018-11-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_id',
            field=models.CharField(default=-1, max_length=30),
        ),
    ]
