# Generated by Django 2.0.4 on 2018-11-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_goods_goods_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_id',
        ),
    ]
