# Generated by Django 2.0.4 on 2018-11-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_remove_goods_goods_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
