# Generated by Django 2.0.4 on 2018-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_auto_20181110_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='他好像不愿意向你介绍自己。', max_length=512),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family_name',
            field=models.CharField(default='无姓', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='given_name',
            field=models.CharField(default='无名', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=12345678910, null=True),
        ),
    ]
