# Generated by Django 2.0.4 on 2018-11-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_auto_20181110_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
