# Generated by Django 2.0.4 on 2018-11-16 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_auto_20181113_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='instationmessage',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Goods'),
        ),
    ]
