# Generated by Django 2.0.4 on 2018-11-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_instationmessage_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='goods',
            name='height',
            field=models.PositiveIntegerField(blank=True, default='600', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='width',
            field=models.PositiveIntegerField(blank=True, default='600', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='goods', width_field='width'),
        ),
    ]
