# Generated by Django 2.0.4 on 2018-11-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_auto_20181116_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='height',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='width',
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='goods'),
        ),
    ]
