# Generated by Django 2.0.4 on 2018-11-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0028_auto_20181116_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='12345678910', max_length=20, null=True),
        ),
    ]
