# Generated by Django 2.0.4 on 2018-11-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_auto_20181116_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
