# Generated by Django 2.0.4 on 2018-11-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_userprofile_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recent_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height', upload_to='', width_field='width'),
        ),
    ]
